version: "2"

run:
  timeout: 5m
  tests: true

output:
  formats:
    text:
      path: stdout

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
  exclusions:
    paths:
      - vendor

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - cherry-go
