run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: cherry-go
  golint:
    min-confidence: 0.8
  govet:
    check-shadowing: true
  misspell:
    locale: US
  unused:
    check-exported: false

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
  disable:
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gosec
        - gocyclo
    - path: cmd/
      linters:
        - gochecknoinits  # Cobra commands use init() by design
        - depguard  # Allow all imports in cmd package
    - path: internal/
      linters:
        - depguard  # Allow all imports in internal packages
    - linters:
        - lll
      source: "^//"  # Exclude long comment lines
    - linters:
        - goprintffuncname
      text: "should be named"  # Our logger functions are intentionally named this way
    - linters:
        - goconst
      text: "(ssh|auto|1\\.0)"  # Small strings that don't need constants
    - linters:
        - gomnd
      text: "(0755|0644|0600)"  # File permissions are clear as numbers
    - linters:
        - unparam
      text: "always nil"  # Some functions return error for consistency
    - linters:
        - dupl
      text: "duplicate of"  # Some duplication is acceptable for clarity