version: "2"

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    text:
      path: stdout
      format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - cherry-go

issues:
  exclude-dirs:
    - vendor
  exclude-rules:
    - path: _test\.go
      linters:
        - gomnd
        - goconst
        - gosec
        - gocyclo
    - path: cmd/
      linters:
        - gochecknoinits
        - depguard
    - path: internal/
      linters:
        - depguard
    - linters:
        - lll
      source: "^//"
    - linters:
        - goprintffuncname
      text: "should be named"
    - linters:
        - goconst
      text: "(ssh|auto|1\\.0)"
    - linters:
        - gomnd
      text: "(0755|0644|0600)"
    - linters:
        - unparam
      text: "always nil"
    - linters:
        - dupl
      text: "duplicate of"
